name: Kernel Build ARM64

on:
  workflow_dispatch:

env:
  BRANCH: lance
  REPO: https://github.com/ioworker0/linux.git

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          path: robot

      - name: system resources
        run: |      
          uname -r && uname -m && echo $(nproc) && free -h
          
      - uses: actions/cache@v4
        id: repo-cache
        with:
          path: .
          key: linux
    
      - name: clone repo
        if: steps.repo-cache.outputs.cache-hit != 'true'
        run: |
          ls -l
          git clone -v ${{ env.REPO }} linux
          
      - name: pre-clean up
        run: |
          cd linux
          git checkout master
          if git rev-parse --verify ${{ env.BRANCH }} >/dev/null 2>&1; then
            git branch -D ${{ env.BRANCH }}
          else
            echo "Branch ${{ env.BRANCH }} does not exist."
          fi
          make clean
          rm -rf .config*
          
      - name: pull branch
        run: |
          cd linux && git pull && git checkout ${{ env.BRANCH }} && git pull

      - name: pre-build kernel arm64
        run: |  
          sudo apt-get update && \
          sudo apt-get install -y gcc-14-aarch64-linux-gnu && \
          sudo dpkg -L gcc-14-aarch64-linux-gnu && \
          sudo ln -s /usr/bin/aarch64-linux-gnu-gcc-14 /usr/bin/aarch64-linux-gnu-gcc
          
      - name: build kernel arm64
        run: |  
          cd linux
          make ARCH=arm64 mrproper
          make ARCH=arm64 allnoconfig
          export ARCH=arm64
          export CROSS_COMPILE="/usr/bin/aarch64-linux-gnu-"
          make olddefconfig
          echo "cat .config"
          cat .config
          echo "Done: cat .config"
          make -j$(nproc)
        
      - name: post-build kernel arm64
        run: |  
          cd linux
          make clean
          rm -rf .config*
